# AI code lmfao
name: CI Pipeline

on:
  push:
    branches:
      - test-ci
      - master
      - release
  pull_request:
    branches:
      - test-ci
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: apartment
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Wait for MySQL service to be healthy
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" --silent; then
              break
            fi
            echo "Waiting for MySQL..."
            sleep 1
          done

      # Create .env file with database credentials
      - name: Create .env file
        run: |
          echo "DB_USERNAME=test_user" >> .env
          echo "DB_PASSWORD=test_password" >> .env

      # Run build and tests
      - name: Build with Gradle
        run: ./gradlew build --scan --no-daemon

      # Run tests
      - name: Run Tests
        run: ./gradlew test

  release:
    needs: build
    if: github.ref_name == 'release'  # Only run if on 'release' branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      # Build the JAR file
      - name: Build JAR
        run: ./gradlew jar

      # Upload the JAR file to GitHub Release
      - name: Upload JAR to GitHub Releases
        uses: actions/upload-artifact@v3
        with:
          name: apartment-app.jar
          path: build/libs/*.jar

      # Create a GitHub Release with the JAR
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token provided automatically

      # Optional: Tag the release
      - name: Tag Release
        run: |
          git tag v${{ github.event.release.tag_name }}
          git push origin --tags

