name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Build JAR
        run: ./gradlew :app:jar

      - name: Remove signatures from JAR file
        run: zip -d app/build/libs/*.jar 'META-INF/*.DSA' 'META-INF/*.RSA' 'META-INF/*.SF' || true

      # Create a GitHub Release with the JAR
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token provided automatically
